default:
  image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  NUGET_PACKAGES_DIRECTORY: '.nuget'

  REPORT_PORTAL_CONFIG_SRC_PATH: "./ReportPortal.config․json"
  REPORT_PORTAL_CONFIG_TGT_PATH: "./ReportPortal.config.json"
  REPORT_PORTAL_PROJECT: "krystsina_pulatava_personal"
  REPORT_PORTAL_API_KEY: ""
  REPORT_PORTAL_LAUNCH_NAME: "EPAM AT Lab 2024.NET"
  REPORT_PORTAL_LAUNCH_DESCRIPTION: "Automated Test Run For Spotify Application"



  
cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - './obj/project.assets.json'
    - './obj/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'

before_script:
  - apt-get update && apt-get install -y wget gnupg
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

build:
  stage: build
  script:
    - dotnet build --configuration Release
    - apt-get update -y
    - apt-get install -y jq 

    - set_config_str() { jq "$1 = \"$2\"" "$REPORT_PORTAL_CONFIG_TGT_PATH" > temp.json && mv temp.json "$REPORT_PORTAL_CONFIG_TGT_PATH"; }
    - set_config() { jq "$1 = $2" "$REPORT_PORTAL_CONFIG_TGT_PATH" > temp.json && mv temp.json "$REPORT_PORTAL_CONFIG_TGT_PATH"; }
  
    - echo "Editing RP UI Configs..."
    - cp $REPORT_PORTAL_CONFIG_SRC_PATH $REPORT_PORTAL_CONFIG_TGT_PATH

    - set_config_str '.server.project' "$REPORT_PORTAL_PROJECT"
    - set_config_str '.server.apiKey' ""

    - set_config_str '.launch.name' "$REPORT_PORTAL_LAUNCH_NAME"
    - set_config_str '.launch.description' "$REPORT_PORTAL_LAUNCH_DESCRIPTION"
  only:
    - dev

test_chrome:
  stage: test
  script:
    - echo "Installing Google Chrome"
    - wget -qO- https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
    - echo "deb [signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update && apt-get install -y google-chrome-stable
    - dotnet test --configuration Release --no-restore
  only:
    - dev
