# .gitlab-ci.yml
default: 
  image: mcr.microsoft.com/dotnet/sdk:8.0 
stages:        
  - test

variables: 
  DOTNET_CLI_TELEMETRY_OPTOUT: "1" # disable telemetry

test:
  stage: test
  services:
    - name: selenium/standalone-chrome:latest 
  script:
    - dotnet restore # Restore all dependencies
    - dotnet test --configuration Release --no-restore
  allow_failure: true # Allows the job to continue even if it fails

