default:
  image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: './'  

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'

before_script:
  - apt-get update && apt-get install -y wget gnupg
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

test_chrome:
  stage: test
  script:
    - echo "Listing files in the current directory:"
    - ls -la
    - echo "Installing Google Chrome"
    - wget -qO- https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
    - echo "deb [signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
    - apt-get update && apt-get install -y google-chrome-stable
    - echo "Updating BrowserType to Chrome in appsettings.json"
    - jq '.AppConfig.BrowserType = "Chrome"' appsettings.json > tmp.json && mv tmp.json appsettings.json
    - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
    - dotnet test --configuration Release --no-restore

test_edge:
  stage: test
  script:
    - echo "Installing Microsoft Edge"
    - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
    - echo "deb [signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list
    - apt-get update && apt-get install -y microsoft-edge-stable
    - echo "Updating BrowserType to Edge in appsettings.json"
    - jq '.AppConfig.BrowserType = "Edge"' appsettings.json > tmp.json && mv tmp.json appsettings.json
    - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
    - dotnet test --configuration Release --no-restore
